apiVersion: v1
description: Serving one image on Kubernetes Ingress
name: one-image
version: 1.20.0-dev
icon: https://raw.githubusercontent.com/sikalabs/charts/refs/heads/master/charts/one-image/icon.png
