apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    {{- range $k, $v := .Values.ingressExtraAnnotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  {{ if .Values.tls }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Release.Name }}-tls
  {{ end }}
  rules:
    - host: {{ required ".Values.host is required" .Values.host }}
      http:
        paths:
          - path: {{ .Values.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
