# Optional
image: sikalabs/signpost:v0.7.0
replicas: 1
host: null
clusterIssuer: letsencrypt
ingressClassName: nginx
ingressExtraAnnotations: {}
ingressTlsDisable: false
tlsKeyBase64: null
tlsCrtBase64: null
signpost_yaml:
