{{- if and .Values.headplane.enabled .Values.headplane.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "headscale.fullname" . }}-headplane
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
  {{- with .Values.headplane.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.headplane.ingress.className }}
  ingressClassName: {{ .Values.headplane.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.headplane.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.headplane.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "headscale.fullname" . }}-headplane
                port:
                  number: {{ .Values.headplane.service.port }}
  {{- if .Values.headplane.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.headplane.ingress.host | quote }}
      secretName: {{ .Values.headplane.ingress.tls.secretName | quote }}
  {{- end }}
{{- end }}
