apiVersion: v1
description: Hello World example chart
name: hello-world
version: 0.17.0
icon: https://raw.githubusercontent.com/sikalabs/charts/refs/heads/master/charts/hello-world/logo.png
home: https://github.com/sikalabs/charts/tree/master/charts/hello-world
sources:
  - https://github.com/sikalabs/charts/tree/master/charts/hello-world
  - https://github.com/sikalabs/hello-world-server
