# Optional
image: sikalabs/hello-world-server
replicas: 1
host: null
path: /
clusterIssuer: letsencrypt
TEXT:
TEXT_SUFFIX:
COLOR:
BACKGROUND_COLOR:
# ingressExtraAnnotations:
#   name: value
#   foo: bar
ingressClassName: nginx
ingressExtraAnnotations: {}
ingressTlsDisable: false
tlsKeyBase64: null
tlsCrtBase64: null
imagePullSecret: null
